name: clean_arc
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.2.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  intl: ^0.18.0
  meta: ^1.9.1
  equatable: ^2.0.5
  go_router: ^12.0.0
  flutter_inappwebview: ^5.8.0
  apps_flyer:
    path: packages/apps_flyer
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  collection: ^1.17.2
  dartz: ^0.10.1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0
  custom_lint: ^0.5.0
  go_router_builder: ^2.3.3
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen
  line_length: 80
  assets:
    enabled: true
    # outputs:
    #   package_parameter_enabled: true
  integrations:
    flutter_svg: true