version: "3.4"
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/hodoan/src/app
      # - ./hodoan/src/app/node_modules
    # command: npm run start:dev
    # depends_on:
    #   # - postgres
    #   - nt-mysql
    # links:
    #   - postgres:postgres
    # env_file: 
    #   - dev.env
      # - prod.env
    ports:
      - "3000:3000"
    # network_mode: "host"
  # nt-mysql:
  #   platform: linux/x86_64
  #   image: mysql:5.7
  #   container_name: nt-mysql
  #   env_file:
  #     - db.env
  #     # - test-infrastructure.env
  #     # - test-program.env
  #   ports:
  #     # from Window: => ":3306"
  #     - "3306:3306"
  #   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
  # postgres:
  #   container_name: db
  #   build:
  #     dockerfile: db.dockerfile
  #     context: .
  #   restart: always
  #   # command: /bin/bash -c "createdb -h localhost -p 5432 -U postgres AntiflammeMobile && pg_restore -C -U postgres -d AntiflammeMobile /var/run/postgresql/2021-12-21.backup"
  #   # command: /bin/bash -c "createdb -h 0.0.0.0 -p 5432 -U postgres DB"
  #   env_file:
  #     - db.env
  #   # ports:
  #   #   - "5432:5432"
  # adminer:
  #   container_name: admin
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     # - postgres
  #     - nt-mysql
  #   ports:
  #       - 8080:8080
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     # - postgres
  #     - nt-mysql